AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# Create queue using sam cli
Description: >
  pes-serverless-application

  Sample SAM Template for pes-serverless-application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PesSQSPollingFunctionHello:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      FunctionName: PesSQSPollingFunctionHello
      Description: This function
      Handler: app.lambdaHandler
      ReservedConcurrentExecutions: 1
      Runtime: nodejs12.x
      Timeout: 30
      Events:
        PesPrioritySqsQueueHello:
          Type: SQS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sqs
          Properties:
            Queue: !GetAtt PesPrioritySqsQueueHello.Arn
            BatchSize: 10
            Enabled: true
  PesPrioritySqsQueueHello:
    Type: AWS::SQS::Queue